name: Hello agile
on:
  push:
    branches: [dev] #triggers when there is a push to the dev branch
  pull_request:
      branches: [main] #triggers when there is a pull request to the main branch
jobs:
 say_hello:
  runs-on: ubuntu-latest
  steps:
    - name: print hello 
      run: echo "hello from github actions"
